[project]
name = "bisection-method"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.3",
    "pandas>=2.3.2",
    "streamlit>=1.49.1",
    "sympy>=1.14.0",
]
